version: '2'
services:
    scrapyd:
        build: ./scrapyd
        hostname: scrapyd
        ports:
            - 6800:6800
        volumes:
            - scrapyd:/var/lib/scrapyd/
        environment:
            HTTP_PROXY: http://proxy:8118
            HTTPS_PROXY: http://proxy:8118
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            FEED_URI: s3://provens3/%(name)s/%(time)s.jl
            FEED_FORMAT: jsonlines
        restart: always
    spiderkeeper:
        build: ./spiderkeeper
        hostname: spiderkeeper
        ports:
            - 5000:5000
        environment:
            SPIDERKEEPER_USERNAME: admin
            SPIDERKEEPER_PASSWORD: admin
            SCRAPYD_SERVER: http://scrapyd:6800
        volumes:
            - spiderkeeper:/var/lib/spiderkeeper
        links:
            - scrapyd
        restart: always
    proxy:
        build: ./proxy
        hostname: proxy
        ports:
            - 8118:8118
            - 2090:2090
        environment:
            TOR_INSTANCES: 25
        restart: always
    pipeline:
        build: ./pipeline
        hostname: pipeline
        environment:
            SPIDERKEEPER_USERNAME: admin
            SPIDERKEEPER_PASSWORD: admin
        links:
            - scrapyd
            - spiderkeeper
            - proxy
volumes:
    scrapyd:
    spiderkeeper:
